"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# DJANGO_ENV=dev(기본) 또는 prod → .env.dev / .env.prod 로드
DJANGO_ENV = os.environ.get('DJANGO_ENV', 'dev')
load_dotenv(BASE_DIR / f'.env.{DJANGO_ENV}')


MEDIA_URL  = "/media/" # 이미지 업로드 경로
MEDIA_ROOT = BASE_DIR / "media"   # BASE_DIR은 settings 맨 위 이미 있음
SECRET_KEY = os.environ.get('SECRET_KEY') # django 암호화용 키

DEBUG = os.environ.get('DEBUG', 'True') == 'True' # 배포시엔 꺼야한다
ALLOWED_HOSTS = ["eventcafe.site", "www.eventcafe.site", "127.0.0.1", "localhost"]


STATIC_URL = '/static/'

# 프로젝트 루트 기준 경로
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', # Admin 사이트 관련 로그
    'django.contrib.auth', # 기본 유저 및 권한 기능
    'django.contrib.contenttypes', # 모델 타입 추적
    'django.contrib.sessions', # 세션 저장
    'django.contrib.messages', # 메시지 프레임워크
    'django.contrib.staticfiles', #정적 파일 관리용
    'rest_framework',
    'corsheaders',  # React와 연결할 때 필요
    'api',          # 생성한 앱 추가
    'django_extensions',  # django-extensions 추가
    'redis',
    "channels",
    "chat",  # 👈 WebSocket app
    'storages'
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 활성화
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application' # 일반 http는 wsgi
ASGI_APPLICATION = 'backend.asgi.application' # websocket은 asgi

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis://127.0.0.1:6379/1")],  # ✅ DB 번호는 URL로 전달!
            "capacity": 1500,
            "expiry": 10,
        },
    },
}


import pymysql
pymysql.install_as_MySQLdb()
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 600,
            'read_timeout': 600,
            'write_timeout': 600,
            'charset': 'utf8mb4',  # ✅ 이거 꼭 넣어주기!
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# settings.py

CORS_ALLOW_ALL_ORIGINS = False  # ❌ 이건 끄고
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # 개발용
    "https://eventcafe.site",     # 배포용 프론트엔드 주소
]

CORS_ALLOW_CREDENTIALS = True  # ✅ 쿠키/세션/인증정보 보낼 수 있게

# settings.py
REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 0


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')         # 여기 사용하고 싶은 Gmail 주소
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')   # Gmail 앱 비밀번호
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# settings.py 가장 아래쪽에 추가하면 됨


from datetime import timedelta

SIMPLE_JWT = {
    "USER_ID_FIELD": "user_id",  # ← 너 모델에서 실제 PK 필드명
    "USER_ID_CLAIM": "user_id",  # ← JWT payload에 들어갈 이름
    
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),     # ✅ access token: 7일
    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=60),   # ✅ refresh token: 30일

    "ROTATE_REFRESH_TOKENS": True,                 # ✅ refresh 요청시 새로운 refresh 토큰 발급
    "BLACKLIST_AFTER_ROTATION": True,              # ✅ 이전 refresh 토큰은 무효화

    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "user_id",
    "USER_ID_CLAIM": "user_id",
    'SIGNING_KEY': SECRET_KEY,
}



import os

IS_APP = os.environ.get("IS_APP") == "true"

if IS_APP:
    KAKAO_REDIRECT_URI = "https://eventcafe.site/user/social/kakao/app-redirect.html"
else:
    KAKAO_REDIRECT_URI = "https://eventcafe.site/user/social/oauth/kakao/callback"
    
KAKAO_REST_API_KEY = os.environ.get('KAKAO_REST_API_KEY')

AUTH_USER_MODEL = 'api.User'

TOSS_SECRET_KEY = os.environ.get('TOSS_SECRET_KEY')

TOSS_CLIENT_KEY = os.environ.get('TOSS_CLIENT_KEY')



DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'eventcafe')
AWS_LOCATION = os.environ.get('AWS_LOCATION', 'media/eventcafe')  # 버킷 내 실제 파일 경로 (media/eventcafe/banners/... 등)
AWS_S3_REGION_NAME = 'ap-northeast-2'  # 서울이면 이거
AWS_QUERYSTRING_AUTH = False  # signed URL 안 쓰는 경우
AWS_DEFAULT_ACL = None

REST_FRAMEWORK = {
        
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # 전체 기본을 로그인 필요로
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}
