# Generated by Django 4.2.20 on 2025-05-23 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaycafe',
            name='liked_events',
            field=models.ManyToManyField(blank=True, related_name='liked_cafes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='birthdaycafe',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
