# Generated by Django 5.1.7 on 2025-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('regular', 'Regular')], max_length=20),
        ),
    ]
