# Generated by Django 4.2.20 on 2025-05-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_birthdaycafe_liked_events_birthdaycafe_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='liked_by',
        ),
    ]
