# Generated by Django 4.2.20 on 2025-05-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaycafe',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthdaycafe',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
