# Generated by Django 4.2.20 on 2025-05-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
