# Generated by Django 5.1.7 on 2025-04-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
