# Generated by Django 5.2.1 on 2025-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
