# Generated by Django 5.1.7 on 2025-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
