# Generated by Django 4.2.20 on 2025-05-31 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_chatroom_members_chatroom_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryterm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_terms', to=settings.AUTH_USER_MODEL),
        ),
    ]
