# Generated by Django 4.2.20 on 2025-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
