# Generated by Django 4.2.20 on 2025-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_dictionaryterm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='display_name',
            field=models.CharField(default='이름없음', max_length=50),
            preserve_default=False,
        ),
    ]
