# Generated by Django 4.2.20 on 2025-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_genre_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryterm',
            name='star_group',
            field=models.ManyToManyField(blank=True, related_name='dictionary_terms', to='api.star'),
        ),
    ]
