# Generated by Django 4.2.20 on 2025-06-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dictionaryterm_star_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryterm',
            name='category',
        ),
    ]
