# Generated by Django 5.1.7 on 2025-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_star_alter_post_is_approved_birthdaycafe_goods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='genre',
        ),
        migrations.AddField(
            model_name='star',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='star',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='star',
            name='display',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
