# Generated by Django 5.1.7 on 2025-05-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_genre_alter_post_is_approved_birthdaycafe_goods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre'),
        ),
    ]
