# Generated by Django 5.1.7 on 2025-05-12 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('venue_type', models.CharField(choices=[('카페', '카페'), ('음식점', '음식점'), ('전시회', '전시회'), ('포토부스', '포토부스'), ('파티룸', '파티룸')], max_length=20)),
                ('road_address', models.CharField(max_length=255)),
                ('detail_address', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='venue_images/')),
                ('rental_fee', models.PositiveIntegerField()),
                ('deposit', models.PositiveIntegerField()),
                ('operating_info', models.TextField(blank=True)),
                ('operating_hours', models.CharField(max_length=255)),
                ('benefits_image', models.ImageField(blank=True, null=True, upload_to='benefit_images/')),
                ('description', models.TextField(blank=True)),
                ('sns_type', models.CharField(blank=True, max_length=50)),
                ('sns_account', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
