# Generated by Django 4.2.20 on 2025-05-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='api.star'),
        ),
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
