# Generated by Django 4.2.20 on 2025-06-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stars/'),
        ),
    ]
