# Generated by Django 4.2.20 on 2025-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_star_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaycafe',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='goods/'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(max_length=500, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='star',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='stars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='benefits_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='benefit_images/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='main_image',
            field=models.ImageField(blank=True, max_length=500, upload_to='venue_images/'),
        ),
    ]
