# Generated by Django 4.2.20 on 2025-06-07 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_birthdaycafe_image_alter_goods_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organizer_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_venues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
