# Generated by Django 4.2.20 on 2025-06-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_organizer_verified_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='business_licenses/'),
        ),
    ]
